server:
  port: 9091
dubbo:
  application:
    name: email_service
  registry:
    address: zookeeper://192.168.79.188:2181
  protocol:
    #配置提供者的端口，-1表示自行查找一个可用的端口
    port: -1
spring:
  mail:
    #配置发送方协议
    protocol: smtp
    #配置smtp服务器地址
    host: smtp.sina.com
    #发送方的邮箱
    username:
    #发送方的密码
    password: