spring:
  datasource:
    url: jdbc:mysql:///springboot
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

#mybatis-plus:
  #mapper-locations: classpath:com\qf\dao\mapper\*.xml
  #type-aliases-package: com.qf.entity
server:
  port: 9090

dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.79.188:2181
  protocol:
    #配置提供者的端口，-1表示自行查找一个可用的端口
    port: -1