server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  consumer:
    check: false
    timeout: 10000
    retries: 3
  application:
    name: login_web
  registry:
    address: zookeeper://192.168.79.188:2181